# 데이터 선택

## 넘파이 실습

In [3]:
# 라이브러리 로딩
import numpy as np # numpy를 np라는 별칭 alias를 사용해서 호출하겠다

In [4]:
# 파이썬 리스트에서 넘파이로 변환

a = [1,3,14,True, "hello"]
b = np.array(a)

In [8]:
# 리스트 원소 데이터 타입 확인

print(a)
for element in a:
    print(f'Data type of {element} : {type(element)}' )

[1, 3, 14, True, 'hello']
Data type of 1 : <class 'int'>
Data type of 3 : <class 'int'>
Data type of 14 : <class 'int'>
Data type of True : <class 'bool'>
Data type of hello : <class 'str'>


In [9]:
# 넘파이 배열 원소 확인
print(b)
for element in b:
    print(f'Data type of {element} : {type(element)}' )

['1' '3' '14' 'True' 'hello']
Data type of 1 : <class 'numpy.str_'>
Data type of 3 : <class 'numpy.str_'>
Data type of 14 : <class 'numpy.str_'>
Data type of True : <class 'numpy.str_'>
Data type of hello : <class 'numpy.str_'>


In [11]:
# 중첩 리스트 생성
a = [[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [12]:
# 중첩리스트 데이터 타입 확인
type(a)

list

In [14]:
# 중첩리스트를 넘파이 배열로 변환
b = np.array(a)
print(b)

# 데이터 타입확인
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [16]:
# 배열의 shape확인
b.shape


(2, 3)

In [17]:
#배열의 차원확인
b.size

6

In [18]:
# 2*3배열을 3*2배열로 변환
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [19]:
#배열 요소 데이터 타입 변경 : 정수 -> 실수
b=np.array(a,dtype=np.float64) # dtype 인수 설정
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
#배열 요소 데이터 타입 변경 : 실수 -> 정수
b=np.array(a,dtype=np.int64) # astype 메서드로 변경
print(b)

[[1 2 3]
 [4 5 6]]


## 넘파이 배열 인덱싱

In [30]:
# 새로운 배열 생성
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [32]:
# 배열 첫번째 요소
print(arr[0])
# 배열 마지막원소
print(arr[-1])

1
5


In [36]:
# 2차원 배열 인덱싱

arr_2d = np.array([[1,2,3],[4,5,6]])

# 2행 3열 원소
print(arr_2d[1,2])

6


### 배열 슬라이싱

In [4]:
# arnage 넘파이 메서드 사용 
# - arange(t시작 숫자 , 끝 숫자): 시작 숫자부터 끝숫자-1 까지의 번호가 나열 되어 저장
# - reshape(행,열) : 원소 개수에 맞춰 배열의 크기 변경 차원도 변경가능

arr_2d = np.arange(1,7).reshape(2,3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
print("첫번째행 가져오기")
print(arr_2d[0,:])
print("세번째열 가져오기")
print(arr_2d[:,2])
print("두번째열까지 모두 가져오기")
print(arr_2d[:,:2])

첫번째행 가져오기
[1 2 3]
세번째열 가져오기
[3 6]
두번째열까지 모두 가져오기
[[1 2]
 [4 5]]


## 판다스(pandas)

### 데이터 생성

In [18]:
import pandas as pd

In [34]:
data = {
    '이름':['아이유','김연아','홍길동','장범준','강감찬'],
    '학과':['국문학','수학','컴퓨터','철학','경영학'],
    '성적':[3.0, 1.0, 3.5, 2.7, 4.0],
}
data

{'이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
 '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
 '성적': [3.0, 1.0, 3.5, 2.7, 4.0]}

In [35]:
df = pd.DataFrame(data)

display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

### 데이터 csv로 저장

In [36]:
# 데이터프레임을 csv로 저장 --> to_csv 
#  to_csv(경로 , sep=콤마로구분, index출력여부)
df.to_csv('./data/student.csv', sep=',', index = False)

In [37]:
# 데이터 불러오기
df = pd.read_csv('./data/student.csv')
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

## 데이터 선택하기

In [38]:
print("1번에서 4번까지")
display(df[1:5])
print("0번에서 3번까지")
display(df[0:3])
print("모든")
display(df[0:])

1번에서 4번까지


이름   학과   성적
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

0번에서 3번까지


이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5

모든


이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

### 인덱싱

In [41]:
display(df['이름'])

display(df[['이름','학과']])

fancy_list = ['이름','학과']

display(df[fancy_list])



0    아이유
1    김연아
2    홍길동
3    장범준
4    강감찬
Name: 이름, dtype: object

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

### 슬라이싱 + 인덱싱

In [43]:
df[1:3][['이름','학과']]

이름   학과
1  김연아   수학
2  홍길동  컴퓨터

### Boolean indexing

In [44]:
# 연산자를 이용하영 인덱싱 수행 
df[ df['학과'] == '수학' ]

이름  학과   성적
1  김연아  수학  1.0

In [47]:
# 성적이 0.5로 나누어지는 행에 접근
df[ df['성적'] % 0.5  == 0]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
4  강감찬  경영학  4.0

In [48]:
df['성적'] % 0.5  == 0

0     True
1     True
2     True
3    False
4     True
Name: 성적, dtype: bool

### pandas 고급 인덱싱 loc& iloc인덱서

In [53]:
#한 개의 행에 대해서만 indexing
df.loc[3]

이름    장범준
학과     철학
성적    2.7
Name: 3, dtype: object

In [54]:
df

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [50]:
# 데이터타입
type(df.loc[3])

pandas.core.series.Series

In [56]:
# 행에 대하여 fancy indexing
df.loc[[1,3]]

이름  학과   성적
1  김연아  수학  1.0
3  장범준  철학  2.7

In [58]:
# 인덱스와 슬라이싱
df.loc[[1,3], : ]

이름  학과   성적
1  김연아  수학  1.0
3  장범준  철학  2.7

In [59]:
# 인덱스와 원하는 컬럼 슬라이싱
df.loc[[1,3], '이름':'성적' ]

이름  학과   성적
1  김연아  수학  1.0
3  장범준  철학  2.7

In [60]:
# 인덱스와 원하는 컬럼 슬라이싱
df.loc[[0,2], '이름':'학과' ]

이름   학과
0  아이유  국문학
2  홍길동  컴퓨터

In [66]:
# 인덱스와 iloc인덱서를 사용
df.iloc[[1,3,4], 0:2]

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [68]:
# loc + boolen indxing
df.loc[ df['성적'] %2 != 0 , ['이름','성적']]

이름   성적
0  아이유  3.0
1  김연아  1.0
2  홍길동  3.5
3  장범준  2.7